### ISSUE TITLE
프로젝트 구조 설정

### ISSUE THREAD

**Issue by withSang** [NewWays-TechForImpactKAIST/frontend#1]
## Summary
vite를 사용한 프로젝트 구조를 만듭니다.

## Todos
- [x] 프로젝트 생성
- [x] Path alias 설정
- [ ] 각종 라이브러리 설정
	- [x] ESLint
	- [ ] 상태 관리(zustand)
	- [x] 라우팅(react-router)
	- [x] 스타일링 (emotion)
- [x] 컴포넌트 디렉토리 구조 만들기
